spring:
  redis:
    host: localhost
    port: 6379
    timeout: 60000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: propertychain-group
      auto-offset-reset: earliest

  web:
    resources:
      static-locations: classpath:/static/

ethereum:
  node-url: http://localhost:8545
  ownership-contract-address: ${OWNERSHIP_CONTRACT_ADDRESS}
  escrow-contract-address: ${ESCROW_CONTRACT_ADDRESS}
  private-key: ${PRIVATE_KEY}

logging:
  level:
    org.springframework: INFO
    com.propertychain: DEBUG
  file:
    name: logs/propertychain.log
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"